# openstack stack create -t lb_template.yaml --parameter subnet_id=cc02caa5-54e9-404f-bb24-da0e8a0b3dc7 --parameter member_ip=192.168.22.5 baptiste_loadbalancer
heat_template_version: 2015-04-30

description: Déploiement d'un Load Balancer avec Octavia

parameters:
  subnet_id:
    type: string
    description: ID du sous-réseau pour le VIP du load balancer
  member_ip:
    type: string
    description: Adresse IP du serveur baptiste-vm

resources:
  # Définition du LoadBalancer
  loadbalancer:
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: { get_param: subnet_id }
      name: baptiste-lb

  # Définition du listener
  listener:
    type: OS::Octavia::Listener
    properties:
      loadbalancer: { get_resource: loadbalancer }
      protocol: HTTP
      protocol_port: 80
      name: baptiste-listener
    depends_on: loadbalancer

  # Définition du pool
  pool:
    type: OS::Octavia::Pool
    properties:
      lb_algorithm: LEAST_CONNECTIONS
      protocol: HTTP
      listener: { get_resource: listener }
      name: baptiste-pool
    depends_on: listener

  # Ajout de membres au pool
  pool_member_1:
    type: OS::Octavia::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_param: member_ip }
      protocol_port: 80
      subnet: { get_param: subnet_id }
    depends_on: pool

  # Health monitor
  health_monitor:
    type: OS::Octavia::HealthMonitor
    properties:
      pool: { get_resource: pool }
      type: HTTP
      delay: 5
      max_retries: 3
      timeout: 5
    depends_on: pool

outputs:
  lb_vip:
    description: Adresse IP virtuelle du load balancer
    value: { get_attr: [loadbalancer, vip_address] }
  lb_vip_port:
    description: Port du load balancer
    value: { get_attr: [loadbalancer, vip_port_id] }